language: python
python:
  - "3.6"
#  - "nightly"

env:
  - DJANGO=2.0.2

before_install:
  - export DJANGO_SETTINGS_MODULE=settings.py
  - export PYTHONPATH=$HOME/builds/safakge/boards
  - export PIP_USE_MIRRORS=true

  # command to install dependencies
install:
  - pip install Django
# command to run tests
script:
  - coverage run --source='.' --omit='venv/*' manage.py test  #used to be just pytest